### ISSUE TITLE
NodeTypes to implement

### ISSUE THREAD

**Issue by ChKoeppel** [neos/Neos.DocsNeosIo#2]
**Link** nodeTypes
- internal "Neos"
- external of 'Product CMS', but internal of Brand 'Neos' (Flow Framework readTheDocs)
- external '3rd party' links: Blog articles, didactical series, ...

example: Wine example Blog of Daniel Lienert (topic 'content modeling')
example: Sandstorm 'The Definitive Guide to Conditional Logic in Neos Fusion'
The objective of these links is to reduce proper editorial work ...! 
(link on content of Flow, link on other readTheDocs articles, ...)
Further, - the docs.neos.io site should figure like a Reference-**POOL** for the historical grown contents that are not replaced yet (ReadTheDocs) ...

**Comment by rolandschuetz** [comment]
@ChKoeppel The NodeType text already allowed links. 

I added the new NodeTypes Buttons, LinkList and Navigation.

See [Navigation](https://instance-c3f94fc9-7bbf-44ec-907a-782da687b353.flownative.cloud/cms/building-your-first-website) and [LinkList](https://instance-c3f94fc9-7bbf-44ec-907a-782da687b353.flownative.cloud/cms/references)
