### ISSUE TITLE
Video from getting started guide offline

### ISSUE THREAD

**Issue by markusguenther** [neos/Neos.DocsNeosIo#24]
Hi the getting started guide is awesome but the video ID Bg5es3oGqWg is not available anymore.
Guess without Roland we could not adjust that, or need to disable the fav icon section.

<img width="1572" alt="Bildschirmfoto 2019-11-05 um 19 59 51" src="https://user-images.githubusercontent.com/1014126/68237241-0e207280-0007-11ea-800c-a321535a2124.png">

**Comment by markusguenther** [comment]
Sorry that I assigned you Roland, but your the only one with access to the videos.
Maybe the ID is just wrong

**Comment by markusguenther** [comment]
Don`t wonder... I hided the favicon part. So it doesn`t look broken ;)

**Comment by rolandschuetz** [comment]
No worry, it's perfectly fine to assign me. Thank for pointing it out, it's fixed.
