### ISSUE TITLE
Update Neos and UI

### ISSUE THREAD

**Issue by maxstoyanov** [neos/Neos.DocsNeosIo#28]
Both Neos and UI are outdated. Loading times are slow and @Sebobo reported that multiple queries are executed twice.

@rolandschuetz Could you update both Neos and the UI?

**Comment by skurfuerst** [comment]
@rolandschuetz sorry for answering only now - no worries about that, we need an update to the latest Neos version anyways before we can enable ES :)

**Comment by skurfuerst** [comment]
FYI: see https://github.com/neos/Neos.DocsNeosIo/pull/25

**Comment by markusguenther** [comment]
Thanks to @kdambekalns for the update ...
