### ISSUE TITLE
Replace Google Analytics with Matomo like on neos.io

### ISSUE THREAD

**Issue by Sebobo** [neos/Neos.DocsNeosIo#36]
@regniets and me did that for neos.io so we would create a PR to change this here too and setup the analytics.
The new solution also works without cookies.

**Comment by ahaeslich** [comment]
Actually, there is no tracking used on the docs pages at the moment as the google analytics tracking is not working since a package upgrade.

**Comment by manuelmeister** [comment]
@markusguenther This has now been resolved, correct?

**Comment by ahaeslich** [comment]
It's working now. Thanks @Sebobo for fixing the config.
